---
- hosts: localhost
  tasks:
    - name: create an ec2 instance
      ec2:
        key_name: sharadakey1
        region: us-east-1
        instance_type: t2.micro
        image: ami-048ff3da02834afdc
        wait: yes
        count: 1
        vpc_subnet_id: subnet-07602016ecc5cbc4f
        assign_public_ip: yes

    - name: just print name
      shell: echo "this is sharadaec2"
